### ISSUE TITLE
Underwhelming trace UX

### ISSUE THREAD

**Issue by kaihendry** [aws/aws-xray-sdk-go#107]
I expected it to show the segment name and offer details like `httpstat`. Am I missing something?
Screencast: https://media.dev.unee-t.com/2019-04-24/aws-sam-xray-go.mp4
Code: https://play.golang.org/p/czrSks9-XKw
https://media.dev.unee-t.com/2019-04-24/aws-sdk-go-xray-feedback.mp4
Using 5ffa743a8b8db87a9d4449c2f63fe95a4a53a8c5

Thank you!

**Comment by awssandra** [comment]
Hi Kaihendry,

It looks like you're running on Lambda with SAM? So, apparently, from my reading, the arguments passed are defined by your SAM template .yaml file. Since you are using an example for reference, I assume only the APIGateway Event is hooked in as an argument, but I can't find where the Lambda context is defined.

Either way, you'll want to set "tracing" as "active", as seen here:
https://github.com/sbstjn/go-lambda-example/blob/master/template.yml

You'll be able to get minimal tracing even without the X-Ray Go SDK this way.
I'm not too familiar with SAM, let me do some more reading and get back to you.

Reading I've done so far:
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
https://itnext.io/creating-aws-lambda-applications-with-sam-dd13258c16dd
https://docs.aws.amazon.com/lambda/latest/dg/go-tracing.html#go-tracing-configuring-sdk

**Comment by kaihendry** [comment]
The default `sam init --runtime go1.x` boilerplate has tracing: https://media.dev.unee-t.com/2019-04-25/template.yaml

I can also confirm **Enable active tracing** is enabled in the lambda console.

**Comment by awssandra** [comment]
Thanks for the update. I am getting in-touch with the SAM developers, will get back to your shortly.

**Comment by luluzhao** [comment]
Hello @kaihendry , I read the [code](https://play.golang.org/p/czrSks9-XKw) you attached and I found out one thing is not correct. AWS X-Ray doesn't support create segment inside lambda function since lambda will generated two segments for customer. You can only create subsegments inside lambda function.

Here I attached a code snippet for you to for create subsegment 
```
import (
    ...
    "github.com/aws/aws-lambda-go/lambda"
    "github.com/aws/aws-lambda-go/lambdacontext"
)

func handler(request events.APIGatewayProxyRequest, ctx context.Context)  (events.APIGatewayProxyResponse, error) {
    ctx, seg := xray.BeginSubsegment(ctx, "checkip.amazonaws.com")
     ...
    seg.Close(nil)

    //another one example with xray.client() instrumention.
    resp, err := ctxhttp.Get(ctx, xray.Client(nil), "https://aws.amazon.com/")
    ...
}
```

Let me know if it works or not. :)

**Comment by kaihendry** [comment]
It didn't work: https://github.com/kaihendry/samXray/blob/master/hello-world/main.go

`[{"path":"github.com/aws/aws-lambda-go/lambda/function.go","line":27,"label":"(*Function).Invoke.func1"},{"path":"runtime/panic.go","line":522,"label":"gopanic"},{"path":"github.com/aws/aws-xray-sdk-go/strategy/ctxmissing/default_context_missing.go","line":45,"label":"(*DefaultRuntimeErrorStrategy).ContextMissing"},{"path":"github.com/aws/aws-xray-sdk-go/xray/segment.go","line":177,"label":"BeginSubsegment"},{"path":"hello-world/main.go","line":29,"label":"handler"},{"path":"reflect/value.go","line":447,"label":"Value.call"},{"path":"reflect/value.go","line":308,"label":"Value.Call"},{"path":"github.com/aws/aws-lambda-go/lambda/handler.go","line":114,"label":"NewHandler.func1"},{"path":"github.com/aws/aws-lambda-go/lambda/handler.go","line":22,"label":"lambdaHandler.Invoke"},{"path":"github.com/aws/aws-lambda-go/lambda/function.go","line":59,"label":"(*Function).Invoke"},{"path":"reflect/value.go","line":447,"label":"Value.call"},{"path":"reflect/value.go","line":308,"label":"Value.Call"},{"path":"net/rpc/server.go","line":384,"label":"(*service).call"},{"path":"runtime/asm_amd64.s","line":1337,"label":"goexit"}]`

Maybe I misunderstood you?

**Comment by luluzhao** [comment]
@kaihendry , the reason why you get this error message is that there is no segment in lambda `context` so that the subsegment cannot be created. In this [line](https://github.com/kaihendry/samXray/blob/master/hello-world/main.go#L27), you provided `context.Background`. I don't think lambda has injected segment into this context since like I said before, lambda will be responsible for generating segments and then injects into lambda `context` so that AWS X-Ray Go SDK could find the segment inside the context and then creating corresponding subsegments. My suggestion would be could you pass `ctx context.Context` as a input parameter into your handler function so that X-Ray Go SDK can use it? For your [reference](https://docs.aws.amazon.com/lambda/latest/dg/go-programming-model-handler-types.html)

**Comment by kaihendry** [comment]
Do you have a minimal code example I could please try instead with https://github.com/awslabs/aws-sam-cli

**Comment by awssandra** [comment]
Hi kaihendry

I've forked your repo, let see if I can unblock you. Will comment back here when I have an update.

**Comment by awssandra** [comment]
Hi kaihendry

I've got the Lambda context setup correctly now. We'll have to figure out how to get the X-Ray daemon running in the SAM Docker environment.

**Comment by luluzhao** [comment]
I read your code, the only thing you need is to inject lambda `ctx` into your handler function. However, I have one question. I found out the handler has `request events.APIGatewayProxyRequest` as its parameter and the `request` is never been used inside the function. I am wondering what is the use case for that `request`? If you don't need it, you can change it to lambda context. I modified your code a little bit and you can try it with [command](https://docs.aws.amazon.com/lambda/latest/dg/lambda-go-how-to-create-deployment-package.html)
```go
func handler(ctx context.Context) (events.APIGatewayProxyResponse, error) {
	ctx1, seg := xray.BeginSubsegment(ctx, "checkip.amazonaws.com")
	resp, err := ctxhttp.Get(ctx1, xray.Client(nil), DefaultHTTPGetAddress)
	seg.Close(nil)

	if resp.StatusCode != 200 {
		return events.APIGatewayProxyResponse{}, ErrNon200Response
	}

	ip, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return events.APIGatewayProxyResponse{}, err
	}

	if len(ip) == 0 {
		return events.APIGatewayProxyResponse{}, ErrNoIP
	}

	return events.APIGatewayProxyResponse{
		Body:       fmt.Sprintf("Hello, %v", string(ip)),
		StatusCode: 200,
	}, nil
}
```

**Comment by awssandra** [comment]
@kaihendry 

Please review the code above, let us know if that helps unblock you.

**Comment by kaihendry** [comment]
<img src="https://s.natalian.org/2019-05-14/1557821274_2560x1440.png">

Thank you for your patience!! Finally understand the [Valid Handler Signatures](https://docs.aws.amazon.com/lambda/latest/dg/go-programming-model-handler-types.html).

So that context should be used everywhere & not context.Background(). I guess one can't rely on http request context either? Is there a way to know I have the right type of context for X-ray?
