### ISSUE TITLE
Question on permission failure debugging

### ISSUE THREAD

**Issue by underscorenygren** [aws/aws-xray-sdk-go#119]
Hi, 

I recently set up the the SDK using Lambda + Apigw. It took longer than it needed because I got snagged on permissions. Apigw turns them on automatically, but I neglected to add the requisite write permissions to my lambda function. My question is twofold. 

Firstly, if a reminder about permissions is not beyond the scope of the README? An addition there would have been helpful to me. 

Secondly, is it possible to report permission-related reporting failures in the log? I had debugging turned on and saw the traces report correctly, which led me astray. I haven't dug deep enough to check if xray swallows these kinds of errors, but if not I figured I'd flag it here.

**Comment by luluzhao** [comment]
@underscorenygren Thank you so much for contacting us regarding your issue. I am wondering how you enable tracing on lambda? By clicking the checkbox in lambda console? If you do in that way, the `write` permission will be automatically added and here is the [link](https://docs.aws.amazon.com/lambda/latest/dg/enabling-x-ray.html) owned by lambda to talk about how to enable tracing. Regardless of this, we should make us README better for customer to instrument there application. I will add this into our backlog to keep track of this issue.

 For your second question, I found out it weird since if you don't have write permission, the segments cannot be send our service. Are you looking at daemon log or your own application log to confirm the traces report correctly? Usually, if you don't have permission, daemon log will report that error. Could you help me to verify it?

**Comment by underscorenygren** [comment]
Hi Lulu,

1. Yes, I enabled xray through the APIGW console, using the checkbox, but I
think I did it out of order, maybe I enabled it before I created the
lambda.

2. I was using the xraylog, which I found in the source and through some
examples around the web. Here's my toy example:
https://gist.github.com/underscorenygren/fba8cb8ed6a813be710eb3c3563ee617

Erik Nygren
(650) 796 6434

**Comment by luluzhao** [comment]
Hi there, I looked at your example and it works right? What kind of message you get from enable xraylog regarding the permission issue? What's more, have you enable the checkbox on lambda console too?

**Comment by underscorenygren** [comment]
Yes, the example works, but does not log any errors when permissions are
not set.

Erik Nygren
(650) 796 6434

**Comment by luluzhao** [comment]
@underscorenygren thanks for confirming the issue. Like I said in the previous thread, you can only find permission error message from X-Ray daemon log since it is X-Ray daemon that calling our X-Ray backend which needs permission. SDK doesn't require any permission to instrument customer's application. SDK only generates segments and send it daemon, which will need permission to call `PutTraceSegments` to send the segment to X-Ray. Hope my explanation is clear and let me know if you still have problems.

**Comment by underscorenygren** [comment]
yeah, I figured this was an issue with how the daemon is set up. Makes
sense, just important to be aware of when you're trying it out.

Erik Nygren
(650) 796 6434

**Comment by luluzhao** [comment]
@underscorenygren I will close this issue for now and feel free to reopen it if you still have questions.
