### ISSUE TITLE
sql - failed to being subsegment

### ISSUE THREAD

**Issue by amwill04** [aws/aws-xray-sdk-go#148]
Unsure if this is an issue or the docs are a little unclear as when implementing `xray` with `sql` it `panics` with the following:

```
"errorMessage": "failed to begin subsegment named 'database_name': segment cannot be found.",
```

Using it as documented

The only way I seem to stop the `panic` is by utilising `beginsegment` is this the correct way to be doing this or am I missing something else?

Thanks

**Comment by luluzhao** [comment]
Hi @amwill04 , thank you for contacting us regarding your issue. The reason why you seeing the error message is because in order to create subsegment for sql, there must be a segment in the context so that the subsegment can be created. All the operation related to SQL will be created as subsegment not segment. The way you are doing is correct which is manually creating a segment. There is another way which is using `xray.Handler` to instrument your server which will create segment automatically and then you can pass the context from `xray.Hander` to inject into SQL so that you won't see the panic.
