### ISSUE TITLE
logging library

### ISSUE THREAD

**Issue by dblooman** [aws/aws-xray-sdk-go#15]
The logging library used in this SDK is pretty terrible.  I would to use a custom logger or at least have something that isn't using inline XML configuration, its 2017.

**Comment by luluzhao** [comment]
Hi Dave, Thank you for using xray Go SDK and I would like to hear why you think the logging library is bad? Is it only the configuration bothering you?

**Comment by cep21** [comment]
The use of global mutable state is one concern I have.

**Comment by dlsniper** [comment]
@luluzhao probably the best way to solve this would be to allow users to inject an ` io.Writer ` implementation for a custom logger. 

I've almost finished a refactoring to do so, but it's pretty big. In it also gets a bit into the other issue #11 due to how it works.

**Comment by DaveBlooman** [comment]
I'm using Apex for lambda functions using Go.  Apex requires the default output for logging to be STDERR, not STDOUT.  It appears that you are setting the console write explicitly.  I would be good to have some control over the type of output, to disable it completely would useful during testing.  

If we could either remove this library and replace it with something more customisable, or just use the stdlib, that would be appreciated.  There is not enough control with the SDK in its current form.

**Comment by sthulb** [comment]
I guess ideally, the SDK would accept an interface for logging, or use the standard "log" pkg if none is specified

**Comment by rantav** [comment]
FWIW, as a temporary workaround I wrote the following function, which simply shuts the logger up.

```go
func ShutTheFuckUp() {
	config := `
<seelog type="sync" minlevel="off">
	<outputs><console/></outputs>
</seelog>`

	logger, err := seelog.LoggerFromConfigAsBytes([]byte(config))
	if err != nil {
		panic(err)
	}
	seelog.ReplaceLogger(logger)
}
```

**Comment by muirrn** [comment]
Here are some problems with the logger:

1. No way to log to a file
2. No way to disable logging
3. Use of global seelog logger is dangerous/naughty (i.e. if the user of xray happens to also use the global seelog logger, xray will overwrite the user's logger)
4. Configuring log level to "error", I still see an "info" level message every time because something logs at the default level before the config is updated.

As others have mentioned, a better way is to accept a logger interface. I recommend a custom interface (e.g. with Debug(), Info() and Error() methods), but io.Writer or stdlib *log.Logger would still be a major improvement. You can maintain the current default behavior of logging to stdout.
