### ISSUE TITLE
Subsegments from existing traceID

### ISSUE THREAD

**Issue by DaveBlooman** [aws/aws-xray-sdk-go#20]
I have a situation where i'm a downstream application, I want to pass the traceID from my C# application to the Go app.  

Looking at the SDK, this doesn't seem possible as subsegment has parent non exported.  Unless i've missed something, is there a way of generating a new subsegment from an existing traceID?

**Comment by luluzhao** [comment]
Hi @DaveBlooman, in this situation, assuming you have included the Go X-Ray SDK with your Go application or micro-service, the Go SDK can generate a new segment for your downstream application. Generally we recommend that each sub-application or micro-service generate a full segment, with subsegments being reserved for sub-system/SDK calls within the sub-application. The Go application will then appear as a separate node(service) on the service map. The new segment for the Go application should use the same Trace-ID as the one generated by the C# application so that a single trace is utilized from end to end.
 
Here are two ways to do it: One way is using our xray.Handler(….) method which will automatically create a new segment for you. The other way is using xray.NewSegmentFromHeader(…..) method to manually pass a header(that already contains a Trace-ID) to create a new segment.

**Comment by DaveBlooman** [comment]
In the end, I used `BeginSegment` and set the parent_id
