### ISSUE TITLE
v1 Stable Release

### ISSUE THREAD

**Issue by codingdiaz** [aws/aws-xray-sdk-go#205]
Is it at all possible to get a v1 non rc release for this package? Right now if you run a go get you get a 0 version which is not compatible with lambda.

**Comment by bhautikpip** [comment]
Hi @codingdiaz,

As per my understanding if you run this command `go get -u github.com/aws/aws-xray-sdk-go` you should be able to get v1.0.0-rc.15. Moreover, we are prioritizing efforts to do v1 non rc release.

**Comment by codingdiaz** [comment]
Awesome. To get this version I had to go get the specific version.

**Comment by bhautikpip** [comment]
**NOTE to the XRay Go SDK customers:** 

There was a customer ask that we shouldn't use init() method for plugins (https://github.com/aws/aws-xray-sdk-go/issues/38) because customers using SDK locally will be importing this. So, we will be removing plugins directory when we do stable GA release and after that customer will have to explicitly call the Init() method  for plugins which is inside awsplugins directory. Since this is a breaking change posting this ahead of time.  Also, as we have mentioned in our README we will be removing xray.SQL API too. Here's a PR which removes plugins and sql.go file (https://github.com/aws/aws-xray-sdk-go/pull/215). I will be merging this right before when we do GA release.

**Comment by bhautikpip** [comment]
Go SDK is now GA! I recently made a v1.0.0 release.

**Comment by mousedownmike** [comment]
Can this be closed?  I get `github.com/aws/aws-xray-sdk-go v1.1.0` when I update.  Seems like this is fixed.

**Comment by awssandra** [comment]
Closing out, thanks for the ping!
