### ISSUE TITLE
Using Xray with stscreds is difficult and awkward

### ISSUE THREAD

**Issue by copumpkin** [aws/aws-xray-sdk-go#208]
I realized I may have submitted this ticket to the wrong tracker, though it sort of feels like the issue spans both projects: https://github.com/aws/aws-sdk-go/issues/3213

Basically, I believe the base SDK doesn't store enough information (`AssumeRoler` in `stscreds` has an insufficient signature) for Xray to do the right thing here, but it might get more attention on this side.

**Comment by bhautikpip** [comment]
Hi @copumpkin,

I was reading through the thread on this (https://github.com/aws/aws-sdk-go/issues/3213)  . Do you think this PR will be able to solve your issue ? (https://github.com/aws/aws-sdk-go/pull/3223). Since this PR introduced GetContext method and they are also working on the issue of propagating down the context.

**Comment by copumpkin** [comment]
Probably! I'll test once that gets merged and see if it's more seamless
