### ISSUE TITLE
Return Context from xray.Handler

### ISSUE THREAD

**Issue by skatsuta** [aws/aws-xray-sdk-go#22]
To capture incoming requests, we use `xray.Handler` to wrap HTTP Handler.
However, since `xray.Handler` does not return inner `Context`,  we need to create another segment using another `Context` to capture other external calls in the wrapped handler.
As a result, segments generated in the handler are separated from request segments, which is not useful to trace each request-to-response flow.

If `xray.Handler` returns `Context` we can create a new subsegment inside the request segment in the wrapped handler by using the `Context`.
Could you consider it?
Thank you.

**Comment by luluzhao** [comment]
@skatsuta , thank you for reaching out to us. I read your issue and the current `xray.hander` method can solve your problem without returning a `Context`. Here I provide an example.

```
    http.Handle("/", xray.Handler(xray.NewFixedSegmentNamer("example"), http.HandlerFunc(func(w http.ResponseWriter, r *http.Request)  {
            w.Write([]byte("Hello!"))
            xray.Capture(r.Context(), "d", func(ctx context.Context) error {
            sess := session.Must(session.NewSession())
            svc := s3.New(sess)
            xray.AWS(svc.Client)
            input := &s3.ListObjectsInput{
                Bucket:  aws.String("xray-daemon"),
            }
            _, _ = svc.ListObjectsWithContext(ctx, input)
            return nil
        })
    })))
    http.ListenAndServe(":8000", nil)
```
As the example above indicates, you can create a new subsegment inside the request segment in the wrapped handler by calling `r.Context` since it returns a `Context`. Let me know whether it works for your implementation or not.

**Comment by luluzhao** [comment]
@skatsuta , I am going to close this issue since it hasn't been updated more than 1 month. Feel free to reopen it or create a new one if you have any problems.
