### ISSUE TITLE
Decouple `NewSegmentFromHeader` from package `http`

### ISSUE THREAD

**Issue by jamiecuthill** [aws/aws-xray-sdk-go#220]
Pre 1.0.0 we were using xray to trace our requests across our microservices using downstream header propagation over our event bus. Since 1.0.0 the `NewSegmentFromHeader` function that we were using to recreate the segment and add new subsegments now requires an http header which we do not have due to using a completely different transport.

What is the correct way to continue adding subsegments to a segment propagated by headers but not over http?

I noticed that a facade segment now exists but unsure if this would be the right way to add subsegments to an existing segment from another service. The documentation only talks about lambda and the example doesn't really say much.

**Comment by bhautikpip** [comment]
Hi @jamiecuthill ,

I believe `NewSegmentFromHeader` API can still be used to create segments if you pass nil to the header field but one more thing to keep in mind is that this approach will always defaults to localized sampling. I think facade segment would not help much in this situation because that is designed to address lambda use case and might not be helpful here. Can I get detailed workflow of how you want to use X-Ray APIs to better help you with approach you can take ? Thank you for opening an issue!
