### ISSUE TITLE
"Segment cannot be found" error druing tracing http call

### ISSUE THREAD

**Issue by RafRabenda** [aws/aws-xray-sdk-go#249]
Hi,

I tried to trace HTTP call to coinpaprika API in Lambda. I used client from documentation:

`myClient := xray.Client(http-client)`

and put it to coinpaprika client as it request http client:

`coinpaprika.NewClient(xray.Client(http.DefaultClient))`

But I received following errors:

[ERROR] Suppressing AWS X-Ray context missing panic: failed to begin subsegment named 'api.coinpaprika.com': segment cannot be found.
[WARN] failed to record HTTP transaction: segment cannot be found.
[ERROR] Suppressing AWS X-Ray context missing panic: failed to end subsegment: subsegment 'api.coinpaprika.com' cannot be found.

How can I point to segment from Labmda context? I tried to create subsegment by my own and catch that trace but it returns the same errors.

In that Lambda tracing calls to DynamoDB works without any problems.

Best 
Rafał

**Comment by bhautikpip** [comment]
Hi @RafRabenda ,

Looks like you're not propagating the context when doing this `coinpaprika.NewClient(xray.Client(http.DefaultClient))` . Therefore, It leads to an issue of 'Segment can not be found' . If you see the below example we're basically passing segment's context while creating subsegment for http calls. I believe you might need to do that. Since we don't allow segment creation inside lambda function code. you can re use lambda's segment context by calling it in function handler like this `func HandleRequest(ctx context.Context) (error) ` and then pass it to the subsegment you're trying to create.

```
resp, err := ctxhttp.Get(ctx, xray.Client(nil), "https://aws.amazon.com/")
    if err != nil {
      return nil, err
    }
    return ioutil.ReadAll(resp.Body)
```

**Comment by RafRabenda** [comment]
Hi @bhautikpip 

Thank you very much for help, now is working as a charm. Maybe it would be good idea to put this information in AWS documentation, because I was following this page: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-httpclients.html and I would have not guessed that I also have to use ctxhttp library.

Best,
Rafał
