### ISSUE TITLE
Lambda query API - maximum allocated quota

### ISSUE THREAD

**Issue by xrn** [aws/aws-xray-sdk-go#278]
Hi,

I have a problem. I am trying to write lambda which is querying to API endpoint and is saving results to dynamoDB - for 1 query everything looks ok - but I have to make ~ 3k requests and I am facing error `This trace has reached its maximum allocated quota. For more information, see AWS X-Ray endpoints and quotas.` 

I was trying to set sampling rules but looks like it do not work:

```
ss, err := sampling.NewCentralizedStrategyWithJSONBytes([]byte(`{
	"version": 2,
	"default": {
	  "description": "A default rule, as included below, is required in any sampling rules file. (service_name, http_method, and url_path are fixed to '*' for this rule.)",
	  "fixed_target": 1,
	  "rate": 0.05
	},
	"rules": [
	  {
		"description": "Example path-based rule below. Rules are evaluated in id-order, the default rule will be used if none match the incoming request. This is a rule for the checkout page.",
		"id": "1",
		"host": "*",
		"http_method": "GET",
		"url_path": "*",
		"fixed_target": 0,
		"rate": 0.0
	  }
	]
  }`))
if err != nil {
	return err
}
cfg := xray.Config{
	SamplingStrategy: ss,
}

if err := xray.Configure(cfg); err != nil {
	return err
}

dynamo := dynamodb.New(session.Must(session.NewSession()))
xray.AWS(dynamo.Client)
...
for _, contract := range apiContracts {
	contractDetails, err := ctxhttp.Get(ctx, xray.Client(nil), URL)
	....		
        _, err = dynamo.PutItemWithContext(ctx, input)
```
	
Even if I created a sampling rule for GET method I am still getting all information in x-ray. Any advice?

**Comment by xrn** [comment]
Looks like I am not able to work with sample rules because `xray.AWS(dynamo.Client)` + `dynamo.PutItemWithContext(ctx, input)` is creating only subsegments and I am not able to manage it. Any idea how can I solve this situation?

**Comment by awssandra** [comment]
Hi xrn,

As per our Lambda documentation, "X-Ray applies a sampling algorithm to ensure that tracing is efficient, while still providing a representative sample of the requests that your application serves. The default sampling rule is 1 request per second and 5 percent of additional requests. This sampling rate cannot be configured for Lambda functions."

https://docs.aws.amazon.com/lambda/latest/dg/services-xray.html

Sampling decisions are made by the Lambda front-end prior to your Lambda function running, because it captures cold-start time and initialization data - this cannot be altered at runtime.

From my understanding, for each invoke of your Lambda, you are doing ~3k dynamo calls? This does sound like the error is correct, the trace has grown too large to accommodate this data. The only way around this would be to reduce the amount of data you are collecting. The PutItemWithContext call is only gathering the minimum data required by our semantics, so there's no way to reduce the data there. 

It sounds like the only way around this would to...
A) Collect data for the entire batch manually and record any errors, instead of using the Dynamo client to record each call
B) Exclude the dynamo calls altogether
C) Or "throttle" the traced calls by using a combination of a traced client and a non-traced client, (but this would lead to incomplete data, and annoying to manage 2 clients)

I would recommend A as a possible work-around.

Thoughts?
Sandra

**Comment by xrn** [comment]
hi, @awssandra 

All points are correct, I was thinking the same way but I would like to confirm it. Thanks - for ppl who will be coming here in the future I replaced `dynamo.PutItemWithContext` with `dynamo.BatchWriteItemWithContext` and for external HTTP request I am using 2 clients
