### ISSUE TITLE
Large external dependencies in `xray` package introduced by v1.5.0

### ISSUE THREAD

**Issue by danielwhite** [aws/aws-xray-sdk-go#310]
The release of v1.5.0 has brought in some heavy-weight dependencies via https://github.com/aws/aws-xray-sdk-go/pull/292 and https://github.com/aws/aws-xray-sdk-go/pull/299. Prior to this release, the `xray` package's dependencies have primarily consisted of dependencies that typically derive from the standard library.

This approach has implications in both binary size and the amount of vendored dependencies.

It would be great if features that incurred heavy external dependencies were offerred in a way that was a easier to opt-in as a consumer of the package.

## Example

Take a fairly simple Lambda that uses an instrumented AWS service, we get the following:

* v1.4.0
  * `go build`: 14MB
  * 117 dependencies (49 internal, 68 external, 0 testing).
* v1.5.0
  * `go build`: 20MB
  * 235 dependencies (67 internal, 168 external, 0 testing).

```go
package main

import (
	"context"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	"github.com/aws/aws-xray-sdk-go/xray"
)

func main() {
	sess := xray.AWSSession(session.Must(session.NewSession()))
	svc := s3.New(sess)

	lambda.Start(func(ctx context.Context, event events.S3Event) {
		for _, record := range event.Records {
			_, err := svc.HeadObjectWithContext(ctx, &s3.HeadObjectInput{
				Bucket: aws.String(record.S3.Bucket.Name),
				Key:    aws.String(record.S3.Object.Key),
			})
			if err != nil {
				panic(err)
			}
		}
	})
}
```

**Comment by magnetikonline** [comment]
I'm seeing similar behaviours to above - agree, we want to stay up to date with the xray package, but ideally would like to avoid the bloat that grpc/etc. has added as we don't use these paths.

**Comment by anuraaga** [comment]
It looks like Go's dead code elimination doesn't work that great for removing the dependencies from a package even if not used. We probably should have made a package for each instrumentation. This was a miss by us, but unfortunately we'd need to do a major version release to move things around at this point.

OpenTelemetry seems to appropriately split packages for each instrumentation so that should not have the problem. We're currently working on Lambda support for it and hopefully that'll provide a better experience going forward.

https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation

In the meantime, is it possible to use the go.mod `exclude` directive to exclude the unneeded transitive dependencies?

**Comment by danielwhite** [comment]
Thanks for the quick response.

IIRC the `exclude` directive is intended for preventing a specific version of a module being loaded so wouldn't be suitable for this.

There is a possibility to [`retract` v.1.5.0](https://blog.golang.org/go116-module-changes#TOC_5.) without needing to resort to a major release. But I realise that this would be a bit of effort and still have non-zero downstream impacts.

Definitely looking forward to OpenTelemetry being a viable option. :+1:

**Comment by anuraaga** [comment]
@danielwhite Yeah I think the impact on downstream of retracting is something we want to avoid if possible, it will still mean code changes for gRPC users using this package I think. Given that, because we are currently working on the OTel based lambda instrumentation for Go (tracked at https://github.com/aws-observability/aws-otel-lambda/issues/101) and the impact of 6MB, while definitely not great, is a lot less than other possible blowups, we're leaning towards not making any changes on this though for any new instrumentations like #309 we will separate out a package. Do you think that this is ok for you and we can close the issue?
