### ISSUE TITLE
Add benchmarks

### ISSUE THREAD

**Issue by tonyghita** [aws/aws-xray-sdk-go#34]
Before I can use AWS X-Ray in my high-throughput service, I need to have some expectation of how it will affect performance. It would be great to start writing benchmarks alongside the tests to get a baseline of CPU and heap usage.

**Comment by haotianw465** [comment]
Thank you for the feedback. We will look into writing benchmark tests.

The overhead of X-Ray might vary based on your sampling rate. But in general, the overhead of running X-Ray is similar to logging. We have multiple customers using X-Ray Go SDK and recording millions of requests each month without any performance issues.

**Comment by tonyghita** [comment]
> The overhead of X-Ray might vary based on your sampling rate

Is there any way to sample only "slower than normal" or requests that have errors? 

I have a fairly high throughput service (1M+ segments per second, unsampled), but I only care to sample on requests in a bad state. I already have an idea of how requests execute in my system in the best case, but I'm interested in learning the failure cases of the system via tracing.

**Comment by haotianw465** [comment]
The way sampling configuration could save overhead is because if the SDK decides to not sample a segment, it will create a dummy object where almost all the setter-like methods and sequential subsegments recording effectively become no-op. Also if you have expensive (relative to your core business logic) annotations/metadata generation code, you can decide to not execute them if the current segment is not a sampled one.

You can implement the sampling methodology you mentioned above on the SDK side. But that probably doesn't add any value in terms of performance overhead. This is a chicken && egg situation. As you can see how not sample a segment could save some overhead, the SDK has to treat every segment a sampled one, because the SDK can only know if the segment is taking long or has error upon close. If the SDK treats every segment not sampled at the beginning, then it will just skip all important data capturing until marked as sampled upon close.

If you have 1M+ segments/sec, 5% sampling rate would still give you enough data points on interesting things. You can adjust the rate based on the route. For example you can set rate to 0 for health check, and a higher value for routes that are more critical.

With rate based sampling the SDK knows the sampling decision upfront, so it can add less overhead. The other benefit of rate based sampling is that you can have a baseline whenever errors or high latency occur. It helps you answer questions like "during error/latency spikes, does average latency across all requests also increase" or "what percentage of requests are impacted during an incident".

Please let me know if it answers your question.

**Comment by tonyghita** [comment]
Thank you for the response.

> If you have 1M+ segments/sec, 5% sampling rate would still give you enough data points on interesting things. You can adjust the rate based on the route. For example you can set rate to 0 for health check, and a higher value for routes that are more critical. You can also tune it as your application evolves.

These are insights I already get from metrics (eg. Statsd -> Graphite or Prometheus). What I'm looking for in a tracing product is insights into how my distributed system works in failure cases.

We're getting a little off-topic from the posted issue. As a maintainer of a high-throughput service, I have two problems:

1. __Impacted service performance due to amount of heap allocations__ (subject of this issue): In benchmarking my application and running in production, I found this library to account for a large amount of heap allocations during any given request. We should at least be tracking these memory allocations with benchmarks as part of the test suite in this library. Once benchmarks are introduced, we can begin to reduce memory allocations. Reducing heap allocations will improve performance, because heap memory is expensive to allocate and expensive to garbage collect.

2. __Utility; low Signal-to-noise ratio__: Sampling all my traffic at a low percentage of overall means my chance of getting data I actually care about (slow requests, requests with errors) is extremely low in a service where 99.9% of requests successful and within latency tolerance. What is the chance of finding information on the 0.1% of misbehaving requests when sampling all traffic at 5%?
