### ISSUE TITLE
support/document usage with aws-go-sdk-v2

### ISSUE THREAD

**Issue by kapilt** [aws/aws-xray-sdk-go#53]
Its not really apparent how to use go xray support with v2 Clients.

**Comment by jason-riddle** [comment]
Any updates on this?

**Comment by luluzhao** [comment]
Hello @jason-riddle 

Sorry for the late reply. `aws-sdk-go` is still under development and we will definitely start testing when v2 version is stable and ready for release. Please stay tuned.

**Comment by alikor** [comment]
If i would work on this feature would we need to be able support v1 and v2 of the API? or like what has been done would with other v2 packages would you create a  github.com/aws/aws-xray-sdk-go-v2?

**Comment by breml** [comment]
@luluzhao Thanks for your reply. My understanding is, that sdk v2 is pretty close to the final release for the following reasons:
1. the latest release is tagged with "preview.5" which sounds to me like "release candidate 5"
2. there have been only few changes in the last few months and from what I can tell, those have been mainly bug fixes. We are using v2 since more than 6 months now and we faced no problem with breaking changes so far.

Do you have some information about a possible release date of v2 of the sdk?

**Comment by danielpsf** [comment]
I'm using Go Mod and I guess everyone that starts a project in Go now will start using Go Mod instead of Glide or Dep.

Turns out I had to migrate to SDK-V2 since V1 do not support Go Mod, and by doing that I lost the capability of using X-Ray and SDK-V2.

I'm looking forward to having support for V2, which will enhance my Serverless apps a lot!

**Comment by laverboy** [comment]
Is there anything that we can do to enable xray tracing of client calls using sdk-v2?

**Comment by mastertinner** [comment]
There is a pretty up to date fork you can use in the meantime: https://github.com/medisante/aws-xray-sdk-go

The fork shows how easy it is to enable v2 in X-Ray without changing any existing code. Would it be an option to create a PR from that fork @luluzhao? After all, the v2 SDK has been out for quite a while now and can hardly still be considered a developer preview (it has seen multiple releases without `preview` in the version number).

**Comment by laverboy** [comment]
I seem unable to use that fork. It looks like the master version with the v2 code in it hasn't been tagged so go only gets the version before the v2 code was added.

So adding the v2 file to the original code base would be great.

**Comment by laverboy** [comment]
Ok so for others who want to use the fork, I was being a bit dim earlier. You can just use 

```go get github.com/medisante/aws-xray-sdk-go/xray@awsv2```

as a replacement. Until the add the code into the official branch.

**Comment by mastertinner** [comment]
@laverboy, you can also just add the following line to your `go.mod` file:

```
replace github.com/aws/aws-xray-sdk-go => github.com/medisante/aws-xray-sdk-go v0.0.0-20190718070426-8b9ae96b5ac3
```

From then on you can use it as `github.com/aws/aws-xray-sdk-go` in your code.

**Comment by Cyberax** [comment]
If you're interested, I've ported the whole XRay SDK to v2 version of the Go SDK, with normal Go modules. No more V1 dependencies!

Link: https://github.com/Cyberax/aws-xray-sdk-go

**Comment by laverboy** [comment]
On more on supporting v2 - this seems to be the number one reason why people are forking this repo. How long is V2 going to be in development?

**Comment by bhautikpip** [comment]
Hi,

[aws-sdk-v2](https://github.com/aws/aws-sdk-go-v2) is still in Developer preview (beta) version. I believe we would still want to wait for [aws-sdk-v2](https://github.com/aws/aws-sdk-go-v2) to go GA (generally available) before we merge any code to our official branch. Meanwhile, community can utilize posted recommendations in this thread. Those recommendations looks neat to me.

**Comment by corymhall** [comment]
@bhautikpip any timeline on this now that the aws-sdk-go-v2 is GA? 

https://aws.amazon.com/about-aws/whats-new/2021/01/aws-sdk-for-go-version-2-now-generally-available/

**Comment by bhautikpip** [comment]
X-Ray Go SDK `v1.6.0` is now released and includes aws sdk v2 support so resolving this issue.
