### ISSUE TITLE
Fully suppress X-Ray SDK logs

### ISSUE THREAD

**Issue by artemnikitin** [aws/aws-xray-sdk-go#60]
We are using X-Ray SDK inside Lambda. SDK version - 1.0.0-rc.5
Our config is:
```go
xray.Configure(xray.Config{
        ContextMissingStrategy: ctxmissing.NewDefaultLogErrorStrategy(),
	LogLevel:               "off",
})
```
But we still continue to get messages such:
```
2018-07-10T21:51:41+02:00 [Error] Suppressing AWS X-Ray context missing panic: failed to begin subsegment named 'unmarshal': segment cannot be found.
```
Is it possible to completely suppress X-Ray SDK output?

**Comment by artemnikitin** [comment]
I figured out what it happened only if `context.Background` is using. Inside Lambda with proper context everything is fine.

**Comment by t-yuki** [comment]
Define your own `ContextMissingStrategy` like:

```
type contextMissing struct{}

func (contextMissing) ContextMissing(v interface{}) {
}

xray.Configure(xray.Config{
        ContextMissingStrategy: contextMissing{},
	LogLevel:               "off",
})
```

**Comment by t-yuki** [comment]
Note that, LogLevel param is ignoring off and critical, huh:

https://github.com/aws/aws-xray-sdk-go/blob/73cfeb4961359ccff6468c1ea21e784684ef4a4c/xray/config.go#L226

**Comment by luluzhao** [comment]
hello @artemnikitin and @t-yuki, thank you for reaching out to us regarding your question. The definition of LogErrorContextMissingStrategy is that instead of throwing exceptions when your instrumented code attempts to record data when no segment provided on the passed `context.Context`, it will log an error and continue. What's more, we haven't support "off" as one of our logging level, which means for now customer cannot completely suppress X-Ray SDK output. In @t-yuki example, it only suppressed the error messages that were related to context missing. However, other type of error message might log. In future, X-Ray Go SDK should support a feature that customer can turn off SDK logs. We are open to accept pull request on this issue. In the meantime, we will add this feature into our backlog and please stay tuned.

**Comment by muirrn** [comment]
Disabling logging is now supported via 
```
func init() {
  xray.SetLogger(xraylog.NullLogger)
}
```

Perhaps this issue can be closed.

**Comment by luluzhao** [comment]
Thanks for @muirrn 's contribution. I will close this issue for now and feel free to reopen it if it is not working.
