### ISSUE TITLE
Support sqlx package

### ISSUE THREAD

**Issue by dlsniper** [aws/aws-xray-sdk-go#8]
Hi,

Thank you for creating this.

I would like to request adding support for ` github.com/jmoiron/sqlx ` in addition to ` database/sql `.
I'd be happy to provide the implementation if you'd be ok with it.
Looking forward for your reply.

**Comment by itsjamie** [comment]
Hello @dlsniper, rather than adding support for the direct `sqlx.DB` type, what about changing this so it that it will accept an interface that `sql.DB` sastifies?

I've referenced #13 here, but I was thinking that if context is necessary, since Go is only supporting Go 1.8, Go 1.9 with the release of 1.9, for a new library it seems like it could only support back to Go 1.8.

Of course, AWS employees would have to comment, but then we could restore the `*sql.DB` compliant structure of the `xray.DB` type, and provide tracing information from there.

Then I don't think you would have to provide a separate implementation for the sqlx package.

**Comment by dlsniper** [comment]
As far as I'm aware there is no interface for ` database/sql.*DB `.
And that would not be possible to begin with since there are methods on ` sqlx.*DB ` that are not present on ` sql.*DB `.

**Comment by itsjamie** [comment]
Correct, there isn't an interface already defined for the `database/sql.*DB` package, however, this package could be changed to accept an interface that "database/sql.*DB" and sqlx.DB both implemented.

Since sqlx.DB is a superset of functionality on top of the existing package, similar to how this library is built now, I believe that a sqlx.DB could be passed if an interface was defined here.

**Comment by itsjamie** [comment]
For example, https://play.golang.org/p/Giy1lbE1W3

**Comment by itsjamie** [comment]
The real issue with that approach would be that this library currently isn't a drop-in replacement for database/sql like sqlx because of the < Go 1.8 support, the type signatures for most of the calls are different to require contexts.

**Comment by dlsniper** [comment]
> because of the < Go 1.8 support

The official support for Go < 1.8 has ended as soon as Go 1.9 arrived. As such, when this library hits 1.0 I don't see any reason on why this shouldn't support Go 1.8+.

The problem with the interface approach is that if anything changes and a function is added, this package is then forced to break compatibility.

I'm working to show a different way to solve this, will take me a bit longer.

**Comment by itsjamie** [comment]
One approach I was considering was creating a proposal for a `sqltrace` package similar to `httptrace` for the stdlib.

https://groups.google.com/forum/#!topic/golang-sql/nGh4Qn5KxCA

I put it in the same google group that kardinos created for the Go 1.8 context additions to database/sql.

**Comment by NZKoz** [comment]
The approach taken by elastic is to have a driver implementation which wraps the underlying drivers

https://github.com/elastic/apm-agent-go/blob/master/contrib/apmsql/driver.go#L39

This makes it much easier to inject into an application using various other DB apis.

**Comment by luluzhao** [comment]
Sorry for the late response. Thanks for all the suggestions and we are definitely going to consider them. This feature has been requested several times from customers and it's already in our backlog. We will prioritize our tasks and release this feature as soon as we can. Thank you for your patience and please stay tuned.

**Comment by noliva** [comment]
@luluzhao any progress towards this issue? I would also be interested in this feature 👍

**Comment by luluzhao** [comment]
@noliva , thank you for your asking. Currently, we're working towards other high priority tasks at this moment but we will definitely come back and revisit this issue in future. Please stay tuned.

**Comment by bhautikpip** [comment]
Hi,

We have recently merged a PR (https://github.com/aws/aws-xray-sdk-go/pull/169) which implements custom SQL driver interface. So now there's a support for Sqlx database utility. So I am closing this issue. Feel free to reopen an issue if you see further problems.

**Comment by amanangira** [comment]
I know this has already been addressed under a separate [PR](https://github.com/aws/aws-xray-sdk-go/pull/169). But why can't we use the below? FYI -- I didn't succeed on getting the traces in my AWS console. 

```
sqlDB, err := xray.SQLContext("snowflake", dsn)
		if err != nil {
			log.Fatal(err)
		}
warehouseClient = sqlx.NewDb(sqlDB, "snowflake")
```
