### ISSUE TITLE
Unable to change internal logging format

### ISSUE THREAD

**Issue by lukestoward** [aws/aws-xray-sdk-go#89]
There are a number of logging messages that are logged to aws/aws-xray-sdk-go/internal/logger which cannot be formatted. At least I am unaware of a method to do so.

My particular issue is that I am using a structured logger which I can configure to work with the XRAY library using `xray.SetLogger`. However, this does not influence the internal logger statements made to `stdout`. I could live with this if the messages logged using the internal logger would correctly append the newline character `\n` to the message to ensure it doesn't conflict with other messages being logged to `stdout`.

The following log calls are missing the newline character, which are messing with the format of my logs.
https://github.com/aws/aws-xray-sdk-go/blob/852dc097d2b83915ece2ab4953e4de711d953626/daemoncfg/daemon_config.go#L71

https://github.com/aws/aws-xray-sdk-go/blob/master/xray/default_emitter.go#L54

Could we either add a mechanism to provide an io.Writer in the same way you can for the `SetLogger` call, but for internal logging, or, more temporarily, ensure that all internal log messages correctly return a newline.

**Comment by yogiraj07** [comment]
Hi @lukestoward ,

Can you explain a bit more on the configuration of your logger? How you are using the `xray.SetLogger()`? I would also like to understand the statement "this does not influence the internal logger statements made to stdout", does it mean the the configuration you use for setting the logger doesn't take into effect for some log statements made by internal/logger and by default it logs to `stdout`? 
The internal logger will invoke `Log()` method of the custom logger set using `xray.SetLogger()`. If you have custom structured logger, the [`Log`](https://github.com/aws/aws-xray-sdk-go/blob/master/xraylog/xray_log.go#L76) method implemented as a part of interface should append `\n` to each log message. The current default implementation adds new line to each log message.

Please let me now if I am missing something.

Thanks,
Yogi

**Comment by lukestoward** [comment]
Hi @yogiraj07, apologies for the delay.

After reviewing what you've said, and digging a little deeper, I think I've found the problem. The function `newGlobalConfig()` is called when I import the xray package, which, given the presents of the `AWS_XRAY_DAEMON_ADDRESS` env var, logs the following:
```
logger.Infof("using daemon endpoints from environment variable AWS_XRAY_DAEMON_ADDRESS: %v", envDaemonAddr)
```
This happens before my application code calls `xray.SetLogger()` and I begin to use the custom logger (just a wrapped io.Writer that satisfies the `xraylog.Logger` interface). I did just notice the comment above the `xray.SetLogger()` which recommends to call only from the init function. This results in the above message being logged to stdout before I can correctly format (append "\n") to the message.

Must I call `xray.SetLogger()` from the init function to ensure the custom logger is used prior to this log message being logged?

**Comment by yogiraj07** [comment]
Hi @lukestoward ,
Thank you for your analysis. In Go, package initialization for the [package](https://golang.org/ref/spec#Package_initialization) dependencies happens before your application package.  When an environment variable for X-Ray daemon address is set, irrespective of using `xray.SetLogger()` in the `init()` of your application, [newGlobalConfig](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/config.go#L45)  calls [GetDaemonEndpoints](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/config.go#L50). When environment variable is passed, we have a [log statement](https://github.com/aws/aws-xray-sdk-go/blob/master/daemoncfg/daemon_config.go#L71) which is emitting in your case.

I think following are the solutions : 

1. If possible, instead of using environment variable to set the daemon address, you can use 	`xray.Configure(xray.Config{DaemonAddr:"localhost:2000"})` to avoid the log entry. (Assuming you have set the custom logger in the init app)

2. Need to refactor the implementation for [newGlobalConfig](https://github.com/aws/aws-xray-sdk-go/blob/master/xray/config.go#L50), which instead calls new method say `daemoncfg.GetDaemonEndpointsFromEnv().UDPAddr` and `GetDaemonEndpointsFromEnv()` doesn't log any statement. 

Please let me know your thoughts.

On the side note, if you use default X-Ray SDK logger, all messages are appended with [`\n`](https://github.com/aws/aws-xray-sdk-go/blob/master/xraylog/xray_log.go#L76). Is your custom logger only appending `\n` to all messages (If yes, I wanted to know why default logger is not sufficient) or having some more custom functionality?

Thanks,
Yogi

**Comment by lukestoward** [comment]
Hi @yogiraj07,
What you have described with the call to `GetDaemonEndpoints` is what i'm seeing. Regarding your solutions, I _could_ avoid using the environment variable in development, however, when I deploy to our numerous environments, the instance running the daemon is hosted elsewhere, so I need to provide the address using the environment variable. I guess I could use a different variable name, but that feels like it defeats the point of the reserved variable name. 

Solution 2 would be useful, particularly to ensure others don't experience the same logging inconvenience.

 > On the side note, if you use default X-Ray SDK logger, all messages are appended with \n

I don't see this happening. Below is an example of my stdout logs.
```
2019-03-22T14:50:53Z [INFO] using daemon endpoints from environment variable AWS_XRAY_DAEMON_ADDRESS: 127.0.0.1:2000{"level":"info","msg":"log level set to debug","time":"2019-03-22T14:50:53Z"}
{"level":"debug","msg":"XRAY: [INFO] using daemon endpoints from environment variable AWS_XRAY_DAEMON_ADDRESS: 127.0.0.1:2000","time":"2019-03-22T14:50:53Z"}
{"level":"debug","msg":"XRAY: [INFO] Emitter using address: 127.0.0.1:2000","time":"2019-03-22T14:50:53Z"}
```

I would expect to see a new line after the "AWS_XRAY_DAEMON_ADDRESS: 127.0.0.1:2000" text, but instead my first custom log line is appended. My logger places each json formatted log on a new line automatically. It's merely an instance of sirupsen/logrus logger.

**Comment by yogiraj07** [comment]
Hi @lukestoward ,
Thanks for the update. If you use just default logger provided by the SDK, are all the log messages not separated by `\n`?  I wasn't able to reproduce  the issue of `\n` not appending to log message locally. 

Irrespective of that, if I use `	xray.SetLogger(xraylog.NullLogger)
` in `init()` of the app and have daemon address set in the `AWS_XRAY_DAEMON_ADDRESS` environment variable, I do see a log entry `[INFO] using daemon endpoints from environment variable...`, which ideally it shouldn't, since the logger is a Null logger (no-op). I will have this issue as a tracker to implement solution 2 as discussed above. A PR is also welcomed.

**Comment by lukestoward** [comment]
Hi @yogiraj07, thanks for your reply. After comparing sources, I've just discovered, somehow, in my project the vendored version of this library has had the "\n" from [here](https://github.com/aws/aws-xray-sdk-go/blob/master/xraylog/xray_log.go#L76) removed. Hence why you're unable to reproduce. My apologies, I can't seem to figure out how/why it was modified before being committed to our repo. It does explain why I wasn't getting the desired formatting.

As for the additional log message, I appreciate the need for your solution 2 under those circumstances. I will try and find the time to open a PR.

Thanks again.

**Comment by lukestoward** [comment]
Hi @yogiraj07, I have opened #96 which implements your solution 2.
